# Generated by Django 4.2.28 on 2026-03-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBonusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('coin_amount', models.PositiveIntegerField(default=10)),
                ('extra_spins', models.PositiveIntegerField(default=0)),
                ('streak_enabled', models.BooleanField(default=False)),
                ('streak_rules_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('reward_type', models.CharField(choices=[('small_coin', 'Small Coin'), ('medium_coin', 'Medium Coin'), ('big_coin', 'Big Coin'), ('extra_spin', 'Extra Spin'), ('premium_day', 'Premium Day'), ('jackpot_virtual', 'Virtual Jackpot'), ('miss', 'Miss (Try Again)'), ('referral_boost', 'Referral Boost'), ('custom_bonus', 'Custom Bonus')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/')),
                ('probability_weight', models.PositiveIntegerField(default=10)),
                ('coin_amount', models.PositiveIntegerField(default=0)),
                ('premium_days', models.PositiveIntegerField(default=0)),
                ('extra_spins', models.PositiveIntegerField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_jackpot_like', models.BooleanField(default=False)),
                ('color_tag', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('spin_cost', models.PositiveIntegerField(default=50)),
                ('free_spins_per_day', models.PositiveIntegerField(default=1)),
                ('max_rewards_visible', models.PositiveIntegerField(blank=True, help_text='Limits rewards showing on UI', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpinBoardReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_weight_override', models.PositiveIntegerField(blank=True, help_text='Overrides default weight', null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_boards', to='rewards.reward')),
                ('spin_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_rewards', to='rewards.spinboard')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('spin_board', 'reward')},
            },
        ),
    ]
