# Generated by Django 4.2.28 on 2026-03-23 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='telegram_premium_coin_value',
            field=models.PositiveIntegerField(default=5000, help_text='Coin value if user chooses to convert to coins'),
        ),
        migrations.AddField(
            model_name='reward',
            name='telegram_premium_months',
            field=models.PositiveIntegerField(default=0, help_text='Telegram Premium subscription months'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('small_coin', 'Small Coin'), ('medium_coin', 'Medium Coin'), ('big_coin', 'Big Coin'), ('extra_spin', 'Extra Spin'), ('premium_day', 'Premium Day'), ('telegram_premium', 'Telegram Premium'), ('jackpot_virtual', 'Virtual Jackpot'), ('miss', 'Miss (Try Again)'), ('referral_boost', 'Referral Boost'), ('custom_bonus', 'Custom Bonus')], max_length=30),
        ),
        migrations.CreateModel(
            name='TelegramPremiumReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('redeemed', 'Redeemed'), ('converted', 'Converted to Coins'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('months', models.PositiveIntegerField(default=1)),
                ('coin_value', models.PositiveIntegerField(default=5000)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_instances', to='rewards.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_premium_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
