# Generated by Django 4.2.28 on 2026-03-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardrequestconfig',
            name='coin_to_uzs_rate',
            field=models.PositiveIntegerField(default=100, help_text="1 Coin necha so'mligini belgilaydi"),
        ),
    ]
