# Generated by Django 4.2.28 on 2026-03-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_rewardrequestconfig_coin_to_uzs_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardrequest',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot of deposited money', null=True, upload_to='withdrawal_screenshots/'),
        ),
    ]
