# Generated by Django 4.2.28 on 2026-03-22 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_balance', models.PositiveIntegerField(default=0)),
                ('reserved_coin_balance', models.PositiveIntegerField(default=0)),
                ('earned_coin_total', models.PositiveIntegerField(default=0)),
                ('spent_coin_total', models.PositiveIntegerField(default=0)),
                ('referral_coin_total', models.PositiveIntegerField(default=0)),
                ('daily_bonus_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reward', 'Reward'), ('referral_bonus', 'Referral Bonus'), ('welcome_bonus', 'Welcome Bonus'), ('daily_bonus', 'Daily Bonus'), ('spin_cost', 'Spin Cost'), ('adjustment', 'Adjustment'), ('reward_request_reserve', 'Reward Request Reserve'), ('reward_request_release', 'Reward Request Release'), ('reward_request_approved', 'Reward Request Approved')], max_length=30)),
                ('amount', models.IntegerField()),
                ('balance_before', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
