# Generated by Django 4.2.28 on 2026-03-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_verification_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Maximum verification attempts per user'),
        ),
        migrations.AddField(
            model_name='task',
            name='requires_screenshot',
            field=models.BooleanField(default=False, help_text='Whether task requires screenshot verification'),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_cooldown_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Minimum time between verification attempts'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification', null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='admin_verified',
            field=models.BooleanField(default=False, help_text='Whether admin has manually verified this task'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time user tried to verify this task', null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot for task verification', null=True, upload_to='task_screenshots/'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of verification attempts made'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='verification_method',
            field=models.CharField(blank=True, help_text='How the task was verified', max_length=20, null=True),
        ),
    ]
