# Generated by Django 4.2.28 on 2026-03-22 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type_snapshot', models.CharField(max_length=50)),
                ('reward_value_snapshot', models.PositiveIntegerField(default=0)),
                ('was_free_spin', models.BooleanField(default=False)),
                ('cost_snapshot', models.PositiveIntegerField(default=0)),
                ('seed_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_logs', to='rewards.reward')),
                ('spin_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_logs', to='rewards.spinboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
