# Generated by Django 4.2.28 on 2026-03-23 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_withdrawal_approved', models.BooleanField(default=True)),
                ('email_withdrawal_rejected', models.BooleanField(default=True)),
                ('email_reward_won', models.BooleanField(default=True)),
                ('email_premium_won', models.BooleanField(default=True)),
                ('email_referral_joined', models.BooleanField(default=True)),
                ('push_withdrawal_approved', models.BooleanField(default=True)),
                ('push_withdrawal_rejected', models.BooleanField(default=True)),
                ('push_reward_won', models.BooleanField(default=True)),
                ('push_premium_won', models.BooleanField(default=True)),
                ('push_referral_joined', models.BooleanField(default=True)),
                ('app_withdrawal_approved', models.BooleanField(default=True)),
                ('app_withdrawal_rejected', models.BooleanField(default=True)),
                ('app_reward_won', models.BooleanField(default=True)),
                ('app_premium_won', models.BooleanField(default=True)),
                ('app_referral_joined', models.BooleanField(default=True)),
                ('app_task_completed', models.BooleanField(default=True)),
                ('app_task_added', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('withdrawal_approved', "To'lov tasdiqlandi"), ('withdrawal_rejected', "To'lov rad etildi"), ('reward_won', "Yutuq qo'lga kiritildi"), ('premium_won', 'Telegram Premium yutildi'), ('referral_joined', "Referal ro'yxatdan o'tdi"), ('task_completed', 'Topshiriq bajarildi'), ('task_added', "Yangi topshiriq qo'shildi"), ('daily_bonus', 'Kunlik bonus'), ('level_up', "Daraja ko'tarildi"), ('system_message', 'Tizim xabari')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
